#!/bin/bash

## This script can build
# -  /react-components on Cif Core Components
# -  /ui.frontend on (BTD, Mr Boston, Fireball, SOCO, Havertys)
# 
# [+] <script.sh> cif mrboston fireball soco btd


## Requirements		
# aemsync 		
# nvm 			
#   -> node v10		
#   -> node v12		


########################################
##  CHANGE THESE FOR YOUR ENVIRONMENT ##
########################################
SCC=''
BTD=''
FB=''
BOST=''
BP=''
HVT=''
NVM_HOME=''
########################################


main() {
	# check for aemsync  
	type aemsync &>/dev/null || 
		{ echo "aemsync is required, but it's not installed. Aborting."; exit 1; }

	# check for nvm
	{ eval $NVM_HOME; command -v nvm >/dev/null; } || 
		{ echo "nvm is required, but it's not installed.  Aborting."; exit 1; }
	
	# print usage and exit if no args
	if [ "$#" -eq 0  ]; then
		usage
	fi
	
	# loop through args and build each 
	for var in "$@"
	do
    		case $var in
			-h | -H | --help | help | Help)
				usage
				;;

			cif | CIF)
				build_cif 
				;;

			BTD | btd | Btd)
	  			build_btd
	  			;;

			mrboston | MrBoston)
	  			build_bost
	  			;;

			fireball | Fireball)
	  			build_fb
	  			;;

			soco | Soco)
				build_soco
				;;
			hvt | HVT | haverty | havertys)
				build_hvt
				;;
		esac
	done
}

# build CIF react-components with node v12
build_cif() {
	echo '[+] building cif react-components';
	eval $NVM_HOME;
	(cd $SCC/react-components/; nvm use 12; npm run webpack:dev && echo 'done';)
}

# build BTD frontend with node v12
build_btd() {
	echo '[+] building BTD';
	eval $NVM_HOME;
	(cd $BTD/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
	(cd $BTD/ui.apps/src/main/content/jcr_root/apps/buffalotracedistillery/clientlibs/; 
		aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
}

# build Mr Boston frontend with node v12
build_bost() {
	echo '[+] building mrboston';
	eval $NVM_HOME;
	(cd $BOST/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
	(cd $BOST/ui.apps/src/main/content/jcr_root/apps/mrboston/clientlibs/; 
	 	aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
}

# build Fireball frontend with node v12
build_fb() {
	echo '[+] building fireball';
	eval $NVM_HOME;
	(cd $FB/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
	(cd $FB/ui.apps/src/main/content/jcr_root/apps/fireball/clientlibs/; 
	 	aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
}

# build Southern Comfort frontend with node v10
build_soco() {
	echo '[+] building soco';
	eval $NVM_HOME;
	(cd $BP/ui.frontend.soco/; nvm use 10; npm run dev && echo 'done';)
	(cd $BP/ui.apps/src/main/content/jcr_root/apps/sazerac-aem-blueprint/clientlibs/soco/clientlib-site-soco; 
	 	aemsync -t http://admin:admin@localhost:4502 -p clientlib-site-soco/;)
}

# build havertys frontend with node v12
build_hvt() {
	echo '[+] building havertys';
	eval $NVM_HOME
	(cd $HVT/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
	(cd $HVT/ui.apps/src/main/content/jcr_root/apps/havertys/clientlibs/; 
	 	aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
}

# print usage and exit
usage() {
	printf '\n[+] ##[+] This script can build\n
# -  /react-components on Saz Cif Core Components\n
# -  /ui.frontend on (BTD, Mr Boston, Fireball, SOCO, Havertys)\n
# 
# [+] <script.sh> cif mrboston fireball soco btd';
	exit 1;
}

main "$@"
